-- Laplace 1.1 -> 1.2: the highway in place.
\echo Use "ALTER EXTENSION laplace UPDATE" to load this file. \quit

-- The highway, in place: the types the resources list, and the mappings between them (laplace.highway names the
-- perf-cache, generated by laplace highway). A type is a slot of a list; its content's ID is its record's.
CREATE FUNCTION laplace_type(list text, value text) RETURNS integer
  AS 'MODULE_PATHNAME', 'laplace_type' LANGUAGE C STABLE STRICT PARALLEL SAFE;
CREATE FUNCTION laplace_type_id(list text, slot integer) RETURNS blake3
  AS 'MODULE_PATHNAME', 'laplace_type_id' LANGUAGE C STABLE STRICT PARALLEL SAFE;
CREATE FUNCTION laplace_type_edges(a text, slot integer, b text) RETURNS integer[]
  AS 'MODULE_PATHNAME', 'laplace_type_edges' LANGUAGE C STABLE STRICT PARALLEL SAFE;
CREATE FUNCTION laplace_highway_fingerprint() RETURNS text
  AS 'MODULE_PATHNAME', 'laplace_highway_fingerprint' LANGUAGE C STABLE PARALLEL SAFE;
